
spring:
  application:
    name: ImoocMerchants
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 257173
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
server:
  port: 9998
logging:
  level:
   top.cllccc: debug
  file: imooc-merchants.log

